### ISSUE TITLE
image html rendering unnecessarily loads blob data

### ISSUE THREAD

**Issue by veritazx** [plone/plone.app.imaging#46]
We are building our own image/media/source etc. tags using the @@images view. The documentation (https://6.docs.plone.org/classic-ui/images.html) states that the way to go (if you cannot use the tag-Method) is view.scale(fieldname, scale, width, height, direction). We did that a lot to access "scale.url". Now we are discovering, that the method "scale" uses "make", which instantiates plone.app.imaging.scale.ImageScale which in turn loads the blob in its init method. Thus most of our image tag rendering loads image blobs. 

We fixed it by putting "url" into the getInfo result dict und now use getInfo to retrieve the url when we need it. That is not really a good solution, because the dict is stored in the annotation storage (where imho the url does not belong). We thought about adding a getUrl Method, but in cases where you need the width, height and url, you end up calling getInfo anyway. 

Most of our scales are not named, the are defined by width and height in the templates that use them. 

Did we do something completely unexpected? Did we misunderstand the documentation? 
Maybe the blob readout in the ImageScale init can be postponed or made optional? 

Thanks a lot,

Peter

**Comment by davisagli** [comment]
Please note: plone.app.imaging is obsolete code that was used for image scaling with Archetypes, and is no longer maintained or supported by the Plone community. Plone 6 (and Plone 5 with Dexterity) uses plone.namedfile for image scaling, and it has a number of improvements, including the ability to generate a link to a scale without actually generating the scaled image yet.

I don't think you did anything unexpected, but I also suspect that loading the blob here was an accidental side effect of how the code was structured.

In your case, since you're supporting an old site that still uses this code, I think your workaround is an okay way to handle it. You could add a new method which does the same thing as getInfo but also generates the URL, instead of storing the URL in the annotation storage.
